Storage docs follow-up
paritytech/ink-docs pull request #149
Opened 2023-02-06 13:30 UTC by xermicus

Explain how to change the root key of contracts storage layout. @xgreenx can you think of situation where this is advisable, or why do we allow setting the key manually?

2023-02-07 22:57 UTC, SkymanOne requested changes
Awesome job again. Just need to update the link

2023-02-07 22:57 UTC, SkymanOne commented on docs/datastructures/custom.md
> +[`#[ink::storage_item]`](https://docs.rs/ink_macro/4.0.0-beta.1/ink_macro/attr.storage_item.html),
```suggestion
[`#[ink::storage_item]`](https://docs.rs/ink_macro/4.0.0-rc/ink_macro/attr.storage_item.html),
```

2023-02-09 14:35 UTC, cmichi commented
Can you update the files in https://github.com/paritytech/ink-docs/tree/master/i18n/es/docusaurus-plugin-content-docs/current/datastructures with the same changes?

For the English text, just wrap it in `<div class="translateTodo"></div>` as in https://github.com/paritytech/ink-docs/commit/211f0b87977c29b647ff3cc26d6dec37f2e76aa9?

2023-02-09 14:36 UTC, cmichi approved these changes

2023-02-09 16:29 UTC, xermicus commented
@cmichi looks like the whole file needs to be translated (it has a TODO translate on top), so I omitted wrapping it in the `translateTodo` div.

2023-02-10 10:59 UTC, cmichi approved these changes

2023-02-10 11:00 UTC, merged