Add contract verification section
paritytech/ink-docs pull request #219
Opened 2023-04-21 14:42 UTC by conor10

I've created an initial draft for a contract verification section for the ink! docs.

I refer to this as a draft as whilst the technical details provided are accurate (although it does duplicate a title image), we want to ensure that the suggested approaches are appropriate for the ink! community. 

We reference the Sirato ink! contract explorer as it provides the most accessible UX for verifying contracts, but everything here is OSS and it would be useful to get the team's input on the verification approach that should be taken that best serves the needs of the ink! community.

For instance, we could remove references to Sirato and just use the verification web service, however, UX would suffer only by having this approach documented (the data ends up in the same place with both approaches).

Web3 Labs wants to ensure that there is a standardised approach to ink! contract verification for the DotSama community, much like [Sourcify](https://sourcify.dev/) in the Ethereum community, where a standardised solution is embraced throughout the ecosystem, instead of having multiple competing services resulting in fragmented contract verification data. 

The sooner we can get verification into the ink! developers' workflow the better, and as there is a working solution available, we want to encourage usage of it.

2023-04-22 19:59 UTC, SkymanOne requested changes
Very well-written and detailed document. I don't have any objections to mentioning Sirato as the code behind it is OS as you mentioned.

I found a few typos and unclear sentences that might need rephrasing.

2023-04-22 19:59 UTC, SkymanOne commented on docs/basics/verification.md
> +complex then EVM-based languages such as Solidity due to the Rust
```suggestion
complex than EVM-based languages such as Solidity due to the Rust 
```

2023-04-22 19:59 UTC, SkymanOne commented on docs/basics/verification.md
> +In order to verify an ink! or any WASM-smart contract the verification
```suggestion
In order to verify an ink! or any Wasm smart contract the verification 
```

2023-04-22 19:59 UTC, SkymanOne commented on docs/basics/verification.md
> +process must rebuild the contract in an identical environment to which it
Could you please rephrase this?

2023-04-22 19:59 UTC, SkymanOne commented on docs/basics/verification.md
> +is a RESTful web service created for verifying smart contracts deployed to WASM.
> deployed to WASM.

Do you mean _deployed on `pallet-contracts`_ or _deployed to Wasm_?

2023-04-22 19:59 UTC, SkymanOne commented on docs/basics/verification.md
> +1. The server streams the archive if is a compressed archive
```suggestion
1. The server streams the archive if it is a compressed archive
```

2023-04-24 16:39 UTC, conor10 commented
Thanks for your feedback @SkymanOne, changes have been incorporated.

2023-04-24 20:16 UTC, SkymanOne approved these changes
Thanks! That looks way better.

2023-04-24 20:21 UTC, merged