Add SubWallet to the ink support wallet list
paritytech/ink-docs pull request #263
Opened 2023-08-25 12:12 UTC by saltict

## Description
SubWallet is the first wallet to support PSP22 and PSP34 tokens written with Ink smart contracts. SubWallet's compatibility enhances the accessibility of these tokens, allowing users to seamlessly manage and interact with them. This pull request aims to enhance the Ink documentation by adding SubWallet as a supported wallet for interacting with Ink smart contracts.

## Details
1. Modified `intro.mdx`: Added SubWallet to the list of supported wallets in the Ink documentation and linked to `https://subwallet.app`.
2. Added `/static/img/wallets/subwallet.svg`.
3. Modified `custom.css` for the wallet section.

## Screenshot
![Changes](https://github.com/paritytech/ink-docs/assets/11567273/1c682ce2-3c4c-407b-accb-f962f4ac7c1d)
This screenshot provides a visual representation of the changes that have been made.

## Testing
I deployed the changes to `https://sw-ink-docs.netlify.app/` for preview purposes.

## Additional Notes
SubWallet has already added support for Ink:
  - SubWallet Issue:
    - [GitHub Issue](https://github.com/Koniverse/SubWallet-Extension/issues/477)
  - Twitter posts about this:
    - [Polkadot Tweet](https://twitter.com/Polkadot/status/1597221322265833472)
    - [ParasHQ Tweet](https://twitter.com/ParasHQ/status/1663956656563310592?s=20)
    - [AstarNetwork Tweet](https://twitter.com/AstarNetwork/status/1666438486591938560)

## Contributors
- @saltict

Your consideration of this pull request is highly appreciated. Thank you!

Sincerely,
Peter Mai

2023-08-26 10:57 UTC, SkymanOne commented
Would be nice if you added a quick article in `Third Party Tools & Libraries` about the supported PSP standards by Subwallet and how they are displayed

2023-08-26 10:58 UTC, SkymanOne approved these changes

2023-08-26 10:58 UTC, SkymanOne commented on docs/intro/intro.mdx
> +## What wallet can I use?
```suggestion
## What wallets can I use?
```
I hope there will be more :)

2023-09-01 20:59 UTC, cmichi commented on docs/intro/intro.mdx
> +## What wallet can I use?
Plus one for this suggestion.

2023-09-01 21:08 UTC, cmichi requested changes
Thanks for the PR!

So strictly speaking you can also use e.g. `polkadot-js` or Talisman as wallets to interact with contracts. So the title "Which wallet can I use?" can appear as frightening if we only refer SubWallet here.

It's clear to me that you mean it in the context of PSP standards supported by wallets. I think it would be best to under the title "Which wallet can I use?" have a bunch of logos and then a table that compares the wallets against each other.

So something like

|   |  SubWallet  | `polkadot-js`  | Talisman  |
|---|---|---|---|
| Interacting with Contracts  | ✅  | ✅  | ✅   |
| NFT's (PSP-34)  |  ✅ | ﹣  | ﹣  |

Please also move the "Which wallets can I use?" section on the intro page below the examples.

PS: Kudos for putting the graphic together like the others! We did it this way so that it also works when the light theme is switched on.

2023-09-09 10:51 UTC, saltict commented
Hi @SkymanOne and @cmichi, thank you for your suggestions.

I have updated the PR. Please help review and approve it if everything is okay

2023-10-05 10:05 UTC, cmichi approved these changes
Thank you a lot for this contribution!

I'm sorry for the delay in response, there were vacations and we're in the process of catching up.

2023-10-05 10:10 UTC, cmichi commented
@saltict Can I ask you to merge `master`? There are some conflicts, they shouldn't be hard to resolve.

2023-10-05 10:44 UTC, saltict commented
> @saltict Can I ask you to merge `master`? There are some conflicts, they shouldn't be hard to resolve.

I resolved the problems by backing up the old master branch, sync-fork, and merging it into new master branch.

2023-10-05 13:21 UTC, merged